#ifndef __Config_H__
#define __Config_H__

#define FIELD_WIDTH 5
#define FIELD_HEIGHT 5

#define WIN_SIZE CCDirector::sharedDirector()->getWinSize()

#define PANEL_CENTER_POINT ccp(WIN_SIZE.width * 0.5, WIN_SIZE.height * 0.4)

#define HOLD_END_MARGIN 3

#define PANEL_TYPE_NUM 6

#define GAME_START_COUNT_DOWN_SEC 3.0

#define HOLD_PANEL_LIMIT 3.0

#define GAME_TIME_LIMIT 10.0

//TODO ステータスの名前見直し、次の処理を知らなくてもいい名前に。STATUS_CHECK_DELETE → STATUS_END_HOLD
enum status
{
    STATUS_INIT_GAME,
    STATUS_END_INIT_SCENE,
    STATUS_GAME_START_COUNT_DOWN,
    STATUS_GAME_START_COUNT_DOWN_END,
    STATUS_TAP_READY,
    STATUS_TAP_START,
    STATUS_HOLD_PANEL,
    STATUS_HOLD_END,
    STATUS_CHECK_DELETE,
    STATUS_DELETE_PANEL,
    STATUS_END_DELETE_PANEL,
    STATUS_WAIT_PROCESS,
    STATUS_GAME_TIME_LIMIT,
    STATUS_RESULT_VIEW
};

#endif // __Config_H__
